### ISSUE TITLE
String的两种实例化方式 | DeppWang's Blog

### ISSUE THREAD

**Issue by DeppWang** [DeppWang/deppwang.github.io#45]
https://depp.wang/2017/07/24/String-Initialization/ 

 关于String的两种实例化方式，我们要先理解类、对象、实例的含义和它们之间的区别与联系。举个形象话的例子：类是抽象化的（如狗），对象是具体化的（如京巴狗），我们常说一个对象（京巴狗）是某个类（狗）的一个实例（instance），所以对象与实例的含义等价。 我们知道，字符串操作是计算机程序设计中最常见的行为。学习String的实例化是非常有必要的。以下是String的源码：123public fi

**Comment by eyesmoons** [comment]
厉害了
